From golang:1.17 as build_k6
WORKDIR /perf
RUN wget https://github.com/grafana/xk6/releases/download/v0.5.0/xk6_0.5.0_linux_amd64.tar.gz \
    && tar -xf xk6_0.5.0_linux_amd64.tar.gz
RUN ./xk6 build --with github.com/grafana/xk6-output-prometheus-remote@latest
RUN wget https://github.com/grafana/k6/releases/download/v0.36.0/k6-v0.36.0-linux-amd64.tar.gz \
    && tar -xf ./k6-v0.36.0-linux-amd64.tar.gz

From python:slim
COPY --from=build_k6 /usr/local/go/bin/go /usr/local/bin/go
COPY perf_test perf_test
RUN pip install -r perf_test/requirements.txt
COPY --from=build_k6 /perf/k6 /k6_test/k6
COPY k6_test/kfs_inference_v2.proto /k6_test/kfs_inference_v2.proto
COPY k6_test/payloads /k6_test/payloads
COPY --from=build_k6 /perf/k6-v0.36.0-linux-amd64/k6 /usr/local/bin/k6
ENTRYPOINT perf_test/runHowitzer.sh
