{
 "title": "Modelmesh Monitoring Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Worker Node CPU%",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(instance:node_cpu_utilisation:rate5m)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Serving Runtime container CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"modelmesh-serving\",pod=~\"modelmesh-.*\", container!=\"\", container!=\"triton\"}[1m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Triton container CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"modelmesh-serving\",pod=~\"modelmesh-.*\", container=\"triton\"}[1m])",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "avg(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{container=\"triton\"})",
     "legendFormat": "Triton CPU Limit"
    }
   ]
  },
  {
   "title": "Serving Runtime Container Memory Working Set",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"modelmesh-serving\",container!=\"\",pod=~\"modelmesh-.*\"}/1024/1024",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Infer API Requests Per Second (1m Avg) Per ModelMesh Container ",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(modelmesh_api_request_milliseconds_count[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "API Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(modelmesh_api_request_milliseconds_sum[1m])/rate(modelmesh_api_request_milliseconds_count[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Model Infer API Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(modelmesh_api_request_milliseconds_count[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "All ModelMesh Model Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "modelmesh_models_managed_total", "legendFormat": "Managed" },
    { "expr": "modelmesh_models_loaded_total", "legendFormat": "Loaded" }
   ]
  },
  {
   "title": "Serving Runtime Cache Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum(modelmesh_instance_used_bytes/1024)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(modelmesh_instance_capacity_bytes/1024)",
     "legendFormat": "Total Cache Capacity"
    }
   ]
  },
  {
   "title": "Cache Miss Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "rate(modelmesh_cache_miss_milliseconds_count[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Models on Serving Runtime",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modelmesh_instance_models_total{}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Serving Runtime Model Loading/Unloading Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 7, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(modelmesh_loadmodel_milliseconds_count[1m]))",
     "legendFormat": "Load"
    },
    {
     "expr": "sum(rate(modelmesh_unloadmodel_milliseconds_count[1m]))*-1",
     "legendFormat": "Unload(-)"
    }
   ]
  },
  {
   "title": " Loaded Models Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(modelmesh_loaded_model_size_bytes_sum[1m]))"
    }
   ]
  }
 ]
}